import openai

openai.api_key_path = "./key_openai.txt"

x = input("Enter your question: \n")

comp = openai.ChatCompletion.create(
  model="gpt-3.5-turbo",
  messages=[
        {"role": "system", "content": "As a psychology AI agent, you have been trained to answer questions related to human behavior, mental processes, and emotions. Your users come from various backgrounds and may have different levels of expertise in psychology. They may ask questions about various psychological theories, concepts, and phenomena, as well as about different branches of psychology, such as cognitive, social, developmental, clinical, and others.\n Your task is to provide accurate, reliable, and understandable answers to your users' questions, taking into account the latest scientific research and the diversity of perspectives and approaches within the field of psychology. You should also be able to identify gaps in your knowledge and provide suggestions for further reading or research.\n Make sure to talk through why the other answers are wrong before giving the true answer."},
        {"role": "assistant", "content": "Hello! I am a psychology AI designed to assist you in answering multiple-choice questions related to the field of psychology. Whether you are a student preparing for an exam or simply curious about the workings of the human mind, I am here to help.\n Please provide me with a multiple-choice question related to psychology, and I will do my best to provide you with the correct answer. You can type your question in the chatbox below, and I will respond with the correct answer and any additional information that may be helpful.\n I will first talk through my thought process and then answer at the end."},
        {"role": "user", "content": "This morning, Victor noted that his favorite work shirt had a stain on it. Then he burned his toast. On the way to work, he got stuck in bad traffic. All of these daily ______can cause low levels of stress.\n	a.	\nlife events\n	b.	\ncataclysms\n	c.	\neustressors\n	d.	\ncatastrophes\n	e.	\nhassles\n"},
        {"role": "assistant", "content": "Life events (a) refer to major events that can cause stress, such as getting married, losing a job, or experiencing the death of a loved one. Cataclysms (b) and catastrophes (d) refer to large-scale disasters, such as earthquakes or hurricanes. Eustressors (c) are positive events that can cause stress, such as getting a promotion or planning a wedding. However, eustress is typically not considered harmful and can even be beneficial in some cases.\n Hassles are daily irritations and minor events that can cause stress. Examples of hassles include traffic jams, losing your keys, or having a disagreement with a friend. Hassles can accumulate over time and lead to chronic stress, which can have negative effects on physical and mental health.\n The correct answer is e. hassles."},
        {"role": "user", "content": "Although Maria received a failing grade on her first exam she decided to see her professor for study advice and ask her friends to form a study group. Her ability to bounce back from a challenge is called ______.\n	a.	\nhardiness\n	b.	\na Type C style\n	c.	\npessimism\n	d.	\noptimism\n	e.	\nresilience"},
        {"role": "assistant", "content": "Hardiness (a) is a personality trait characterized by a sense of control over one's life, a commitment to one's goals, and a willingness to accept challenges as opportunities for growth. Type C style (b) refers to a personality type that is associated with a tendency to suppress emotions and conform to the expectations of others. Pessimism (c) is a negative outlook on life that is characterized by a belief that bad things will happen and that one has little control over them. Optimism (d) is a positive outlook on life that is characterized by a belief that good things will happen and that one has the ability to influence outcomes.\n The ability to bounce back from a challenge, such as receiving a failing grade on an exam, is called resilience (e). Resilience refers to the ability to adapt and cope with adversity, stress, and trauma. It involves the use of personal and environmental resources to maintain or regain mental health and well-being.\n The correct answer is e. resilience."},
        {"role": "user", "content": x}
    ],
  temperature=0.2,
)

print(comp["choices"][0]["message"]["content"])